trace:
  endpoint: http://jaeger-trace.startops.local/api/traces

data:
  database:
    driver: mysql
    source: {user}:{passwd}@tcp(127.0.0.1:3306)/{db}?charset=utf8mb4&parseTime=True&loc=Local
    maxIdleConns: 10
    maxOpenConns: 10

dns:
  dns:
  - "223.5.5.5:53"
