trace:
  endpoint: http://jaeger-trace.startops.com.cn/api/traces

data:
  database:
    driver: mysql
    source: autocert:KxJ82S0ja0Xjk@tcp(127.0.0.1:3306)/autocert?charset=utf8mb4&parseTime=True&loc=Local
    maxIdleConns: 10
    maxOpenConns: 10

dns:
  dns:
  - "223.5.5.5:53"
